### ISSUE TITLE
Can´t install this

### ISSUE THREAD

**Issue by mercuryin** [rtorchia/Smartthings-Hikvision-Events#2]
Hello,

I am following your instructions for addings this smartapp to my smarthings hub.

When I do this;
( Tap on the Update from Repo button and select the Hikvision-Events repo.
Select the Hikvison Motion Sensors application and install it. )

There is nothing to add on the following window, just click to "  " smartapps/rtorchia/Hikvisionevents.src/Hikvisionevents.groovy " and it says Update 0 Created 0 Skipped 1 erros.

Thanks

**Comment by mercuryin** [comment]
Sorry I forgot to add the code manually for the smartapp and the device handler manually. I don´t know why I thought it will do it automatically. Sorry about that.

Now I´m stucked here;

Hikvisioneventsserver Setup

( Edit the hikvisionevents.cfg file. (a) Enter in the IP address and login information for your Hikvision NVR. (b) Change the Smartthings host to where your IDE resides (usually the URL of your IDE). Add the accessToken and appkey/appID of the SmartApp. To find it, open your IDE and go to Locations, then select the smartapps link in the location you installed the app, then find it in the list and click on its name. The access token is found in the Application State. You can find all three parameters in the endpoint field of the form https://{{host}}:443/api/token/{{accessToken}}/smartapps/installations/{{appId}}/ (c) Edit the names of the cameras attached to your NVR.
Run the python script. You can setup events and alarms in your Hikvision NVR using its web interface or the client software. When an event is first triggered it will be added automatically as a device to Smartthings. )
 Once I have my info added how I run the phyton script and where I have to add that file ? Do I need a separated pi for that ? Thanks

**Comment by mercuryin** [comment]
root@DietPi:/home/dietpi# python HikvisionEventServer.py 
Traceback (most recent call last):
  File "HikvisionEventServer.py", line 10, in <module>
    import requests
ImportError: No module named requests

**Comment by rtorchia** [comment]
Try updating now from the ST IDE for the repo (there was a typo that I just only noticed that prevented it from working).
You will need python 3.8 to run the script. Just place the scripts with the config file the same directory, and then run the script from the shell.
The error for the "requests" module is because your install of python doesn't have that module installed. From a shell issue the command "pip install requests". You may need to add any other modules that you may not have.

**Comment by mercuryin** [comment]
Thank you so much, working like a charm right now. The only additional modules needed with a default vmware rasperry image was " requests " and " hikvisionapi ".

It works better than ifftt and ezviz app !

![capture](https://user-images.githubusercontent.com/45206429/79899064-22fd9080-8404-11ea-8337-d1525deeb6d3.jpeg)
